{
 "title": "ML Model Serving & Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route, status_code) (\r\n  rate(http_requests_total{status_code=~\"4..|5..\"}[5m])\r\n)",
     "legendFormat": "{{route}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Average Inference Latency (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\r\nsum by (model_version) (\r\n  model_prediction_duration_seconds_sum\r\n)\r\n/\r\nsum by (model_version) (\r\n  model_prediction_duration_seconds_count\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (route) (\r\n  rate(http_requests_total[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions by Model Version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_version) (\r\n  model_predictions_total\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}